# 시리즈 정리

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

###  데이터를 분석하려면 데이터 프레임 형태로 만들면 됨
###  행(인스턴스, 실제값), 열(속성, 특성)을 가지는 2차원이 됨
###  파이썬에서는 데이터 분석시 사용하는 2차원의 데이터를 다루기 위해 클래스(부품)을 만듬
###  1. 속성정의(컬럼값 정의) 2. 값정의 => key - value

In [8]:
dics = { "name" : ["홍길동","박길동","김길동","송길동"], "age" : [10, 20, 30, 40]} #딕셔너리 형태 ~> 데이터 프레임에 넣기
df = pd.DataFrame(dics)
df
# 인덱스가 자동으로 붙는 객체(오토인크리먼트) => 데이터프레임 (Series + Rangeindex의 결합)

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

In [12]:
#enumerate연습해보세여
for i, item in enumerate(df['name']):
    print(i, item)

0 홍길동
1 박길동
2 김길동
3 송길동


In [17]:
for i, item in enumerate(df.to_list):
    print(i, item)

0 name
1 age


In [5]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
type(df.index) #Rangeindex 부품 , class

pandas.core.indexes.range.RangeIndex

In [8]:
#시리즈는 인덱스 + 리스트
df.name # == df['name']

0    홍길동
1    박길동
2    김길동
3    송길동
Name: name, dtype: object

In [9]:
type(df['name']) #데이터프레임안에서 나머지 열은 시리즈임

pandas.core.series.Series

In [12]:
df_list = df.index.tolist() #인덱스만 목록으로 가져오고 싶으면 list로 변경해서 사용
df_list

[0, 1, 2, 3]

In [17]:
df['name'].index #시리즈는 인덱스와 리스트로 이루어져있기 때문에 가능

RangeIndex(start=0, stop=4, step=1)

In [18]:
df_name_list = df['name'].index.tolist() #리스트로
df_name_list

[0, 1, 2, 3]

In [19]:
df['name'].values #시리즈에 해당하는 값들은 배열에 담겨짐

array(['홍길동', '박길동', '김길동', '송길동'], dtype=object)

In [22]:
df_name_values = df['name'].values.tolist()
df_name_values

['홍길동', '박길동', '김길동', '송길동']

In [23]:
df_name_values2 = df['name'].tolist() #Series를 리스트로 변환, 인덱스가 생략한 형태의 리스트가 됨
df_name_values2

['홍길동', '박길동', '김길동', '송길동']

## 데이터프레임을 만드는 방법
***
### 1) dic사용
### 2) csv, excel파일 읽어오기
### 3) df에 values(값), column을 지정

In [24]:
#데이터를 지정
#df2 = pd.DataFrame(data = [**2차원 형태의 데이터가 들어가야함], columns =  ['name', 'age'] ) 
df2 = pd.DataFrame(data = [['홍길동',100],['김길동',200]], columns =  ['name', 'age'] ) 
df2

name  age
0  홍길동  100
1  김길동  200

In [26]:
name_values = ["홍길동","박길동","김길동","송길동"]
age_values = [10, 20, 30, 40]
df3 = pd.DataFrame({ "name" : name_values , "age" : age_values})
df3
# 인덱스가 자동으로 붙는 객체(오토인크리먼트) => 데이터프레임 (Series + Rangeindex의 결합)

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

### Series => DataFrame

In [30]:
df_name = df['name'].to_frame()
df_name

name
0  홍길동
1  박길동
2  김길동
3  송길동

In [31]:
type(df_name)

pandas.core.frame.DataFrame

In [33]:
type(df2.columns)

pandas.core.indexes.base.Index

In [34]:
df2.columns.tolist()

['name', 'age']

In [36]:
data = [100,200,300] #1차원 리스트
sum(data)#파이썬에서 제공하는 함수(기본)


600

In [37]:
max(data) #파이썬 기본 함수

300

## ndarray : 다양한 차원의 데이터(배열)를 하나의 클래스로 다루기 위해 만들어짐 
***
## n : 숫자(number) d : 차원(dimension) array : 배열


In [40]:
arr1 = np.arange(15) #리스트 생성해주는 numpy객체의 함수, 1차원
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
#2차원으로 만들기
arr1_reshape = arr1.reshape(3, 5) #원하는 차원으로 만들어주기 : reshape
arr1_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
type(arr1_reshape)

numpy.ndarray

In [47]:
# Mask
mask = np.zeros(2) #1차원 배열 만드는 중
mask

array([0., 0.])

In [48]:
mask2 = np.zeros((3, 4)) #2차원 배열 만들기 튜플형태
mask2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
#2차원 배열만들기
arr2 = np.array([[1,2,3],[4,5,6]] , dtype = np.float64)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [55]:
#2차원 배열만들기
arr3 = np.array([[7,8,9],[10,11,12]] , dtype = np.float64)
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [57]:
#행렬의 연산을 할 수 있음
arr2 + arr3

array([[ 8., 10., 12.],
       [14., 16., 18.]])